# Generated by Django 5.0.1 on 2024-01-16 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='coach',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='establishment_year',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='match_count',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='total_rating',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=None, null=True)),
                ('start_date', models.DateField(default=None, null=True)),
                ('end_date', models.DateField(default=None, null=True)),
                ('championship_name', models.CharField(max_length=100)),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='championship_winner', to='app.team')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_score', models.CharField(max_length=10)),
                ('championship_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.championship')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_team1', to='app.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_team2', to='app.team')),
            ],
        ),
        migrations.CreateModel(
            name='Standings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=None, null=True)),
                ('defeats', models.IntegerField(default=None, null=True)),
                ('victories', models.IntegerField(default=None, null=True)),
                ('draws', models.IntegerField(default=None, null=True)),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.championship')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.team')),
            ],
            options={
                'unique_together': {('championship', 'team')},
            },
        ),
    ]
